apiVersion: v1
kind: Secret
metadata:
  name: video-secrets
  namespace: video-processing
type: Opaque
stringData:
  # MinIO Credentials
  MINIO_ACCESS_KEY: "minioadmin"
  MINIO_SECRET_KEY: "minioadmin123"
  
  # RabbitMQ Credentials
  RABBITMQ_DEFAULT_USER: "admin"
  RABBITMQ_DEFAULT_PASS: "admin"